[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lastfm-cli"
version = "0.1.0"
description = "CLI for viewing last.fm history"
dependencies = ["requests"]

[project.scripts]
lastfm = "lastfm.main:main"
